# Generated by Django 4.2.16 on 2024-09-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(choices=[('3Б', '3Б'), ('2А', '2А'), ('1А', '1А'), ('2Б', '2Б'), ('1Б', '1Б'), ('3А', '3А')], default='1А', max_length=2, verbose_name='Осень'),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(choices=[('3Б', '3Б'), ('2А', '2А'), ('1А', '1А'), ('2Б', '2Б'), ('1Б', '1Б'), ('3А', '3А')], default='1А', max_length=2, verbose_name='Весна'),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(choices=[('3Б', '3Б'), ('2А', '2А'), ('1А', '1А'), ('2Б', '2Б'), ('1Б', '1Б'), ('3А', '3А')], default='1А', max_length=2, verbose_name='Лето'),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(choices=[('3Б', '3Б'), ('2А', '2А'), ('1А', '1А'), ('2Б', '2Б'), ('1Б', '1Б'), ('3А', '3А')], default='1А', max_length=2, verbose_name='Зима'),
        ),
    ]
